### ISSUE TITLE
Async updates

### ISSUE THREAD

**Issue by yovanoc** [inv2004/coinbase-pro-rs#15]
Hello!

Have you planned to update this project with new async std and/or tokio updates?

Thanks!

**Comment by inv2004** [comment]
Hello,
I was trying long time and found that generators does not work good and
very unstable. I do not remember # of the issue I commented about it in
rust.

Probably I will try one more time a bit later.

Thank you for reminding me.

Regards,

**Comment by yovanoc** [comment]
No worries, I just made a little trading bot for fun so nothing to worry about x)

Was just a little question. So thank you for your work and I start to watch de project :)

**Comment by favilo** [comment]
I just sent a PR to address this, since I was interested in it, too. #16

**Comment by inv2004** [comment]
@favilo Thank you, I will publish it like major version update after tests passed

**Comment by inv2004** [comment]
@favilo Unfortunately I do not want to push version until tests is complete, but I do not have time to complete it now.

Please point cargo to git

**Comment by favilo** [comment]
No problem. I am actually writing a lot of code to update this crate to a more standardized 2018 edition of the code.

Moving tests into the individual src files. Removing `#[macro_use]` and the `extern crate` lines. Using `thiserror` instead of `failure`. Marking enums as `#[non_exhaustive]` so we don't have to update the major version every time we add an option to it.

I'm also going to be adding some of the missing API. In particular, `get_account_history` currently doesn't work, because we are missing a `Conversion` type.

I was planning on just dropping a large PR, but I don't mind breaking it apart if you'd prefer.

**Comment by inv2004** [comment]
@favilo 
Thank you for the huge PR you have made! And especially about tokio 0.3 part.

0.6.2 pushed
